rfc28: add new RFC for resource acquisition
flux-framework/rfc pull request #253
Opened 2020-06-27 19:15 UTC by garlick

I thought it would make sense to complement RFC 27 with an RFC for the other major scheduler interface:  `resource.acquire`.  This will need an update once we settle on the "resource object" format (*R*).

2020-06-30 19:13 UTC, dongahn commented
@garlick: I have a few tasks that I need to finish up soon. But so that you now, I do plan to review this. You can assign me as one of your reviewers if you want.

2020-06-30 19:30 UTC, garlick commented
Any comments would be welcome, thanks.  I'm not in any rush to merge this - we may want to leave it open until we are are further along with Rv2.

2020-07-17 00:45 UTC, dongahn commented on spec_28.rst
> +Note: at this time, execution targets map directly to Flux broker ranks,
Can we say: version 1 maps does this mapping at the Flux broker rank level instead of using a loose term: "at this time?" 

That can make this statement (and thus this v1 RFC) a bit tighter. 

If and when we change the exec target levels, we will probably update the version to something higher anyway?

2020-07-17 00:56 UTC, dongahn commented on spec_28.rst
> +includes a *resources* object and an *up* idset (RFC 22) defining which of the
So the plan is to keep the current protocol as is? If it will not be too time consuming, I think we should consider introducing a few enhancements to V1 protocol to make the scheduler architecture written on top of V1 a bit cleaner.

1. In addition to `resources`, we can introduce `grow` key or similar so that the scheduler doesn't have to parse out `resources` to get the execution target set.

2. "unexclude" can also map to the same "grow" key, and this would be the special case of elasticity that V1 can support and allow schedulers to add some elastic features. 

3. "unexclude" currently doesn't generate a response and this probably needs to be addressed before V1 is cast in stone? Or document this deficiency? 

4. Currently an "exclude" event shows up as "down" to the scheduler, and this breaks the satisfiability semantics of schedulers. This would be better mapped to the "shrink" key or similar, and so that satisfiability is calculated based on this resulting resources. "down" resources shouldn't affect  satifiability.

2020-07-22 16:56 UTC, garlick commented on spec_28.rst
> +includes a *resources* object and an *up* idset (RFC 22) defining which of the
Yes I think we can make a small change to the protocol to address this.  Sorry I was moving fast when resource was created and had thought the exclusion set change was not likely to be a high priority TOSS production issue so had pushed it off, but given that it's so easy to fix, that was short sighted.

The first response currently includes "resource" and "up" keys.  I would propose that we add an "include" key that includes the idset for execution targets that should be considered for satisfiability.

Then for subsequent response we would also send, as needed, "include" and "exclude" keys to allow this list to be changed.

(I was wondering if we should call those grow and shrink but I think maybe grow might eventually need to set another resource object and so we might want to reserve those as more advanced operations to be added later?)

2020-07-22 17:17 UTC, grondo commented on spec_28.rst
> +includes a *resources* object and an *up* idset (RFC 22) defining which of the
Since we're changing the protocol, could `resource` be renamed `grow` (or something more appropriate), to reduce the specialness of the first response, since technically the first response is just a "grow from nothing"?

Sorry if that is a dumb idea.

2020-07-22 17:57 UTC, garlick commented on spec_28.rst
> +includes a *resources* object and an *up* idset (RFC 22) defining which of the
I think the first response _Is_ special since you really cannot tell the job manager "ready" until you have some resources, otherwise all jobs would be rejected as unsatisfiable.

That said, I'm fine with renaming `resource` to `grow` if that makes more sense to people.  What say you @donghan?  I see the use of "grow" in your PR, does this change fit?

2020-07-22 19:08 UTC, grondo commented on spec_28.rst
> +includes a *resources* object and an *up* idset (RFC 22) defining which of the
Sorry, I didn't phrase my question correctly. Of course the first response is special, but why does the internal protocol/keys that tell the scheduler to add some resources have to be special?

Actually, on my ride I was wondering if we could have `grow`/`shrink` or `add`/`remove` keys under a `resource` key for more organization (ie. no ad hoc keys). The first response, plus any future response that wants to "add" resources or "grow" would set `resource.add`. In the future a `resource.subtract` or `remove` could be used to "shrink".

> since you really cannot tell the job manager "ready" until you have some resources, otherwise all jobs would be rejected as unsatisfiable.

It also occurred to me that there will be a similar problem with "grow". If you are in the middle of a grow operation and some jobs are submitted that can take advantage of the new resources, they will rejected as unsatisfiable until the scheduler has received the resource response with the new resources.

2020-07-22 19:45 UTC, garlick commented on spec_28.rst
> +includes a *resources* object and an *up* idset (RFC 22) defining which of the
That sounds reasonable.

On the last point, it seems like a "growable" instance will want to disable or relax the satisfiability check since it's no longer impossible jobs that exceed available resources to run.  Maybe if there are boundaries on its growth it could check those?

2020-07-22 19:58 UTC, dongahn commented on spec_28.rst
> +includes a *resources* object and an *up* idset (RFC 22) defining which of the
Yes, grow/shrint and up/down are exactly how fluxion is mapping resource.acquire keys. So this should work very well currently as well as our future elastic scheduling support.

2020-07-22 19:58 UTC, dongahn commented on spec_28.rst
> +includes a *resources* object and an *up* idset (RFC 22) defining which of the
https://github.com/flux-framework/flux-sched/blob/5f58fc00168583820e3c9ae210521ea81abbdc39/resource/modules/resource_match.cpp#L702

2020-07-22 20:00 UTC, dongahn commented on spec_28.rst
> +includes a *resources* object and an *up* idset (RFC 22) defining which of the
> On the last point, it seems like a "growable" instance will want to disable or relax the satisfiability check since it's no longer impossible jobs that exceed available resources to run. Maybe if there are boundaries on its growth it could check those?

Yes something like this. But I think even without this, the code should support the workloads pretty well for awhile.

2020-07-22 20:13 UTC, grondo commented on spec_28.rst
> +includes a *resources* object and an *up* idset (RFC 22) defining which of the
> On the last point, it seems like a "growable" instance will want to disable or relax the satisfiability check since it's no longer impossible jobs that exceed available resources to run. Maybe if there are boundaries on its growth it could check those?

It would be nice if *any* flux instance could turn into a growable instance. In my mind this would indicate a clean design, vs a set of conditional logic for growable vs non-growable instance.

It seems like there might be a use for a workload requesting an instance to grow, then submitting more jobs to be scheduled which would take advantage of the increase in resources. In that case, the initial `resource.acquire` response is just a little less special (is the only point I was trying to make initially).

Is this an impossible design?

2020-10-16 23:29 UTC, dongahn commented
@garlick: was there any change to this that I need to review?

2020-10-16 23:30 UTC, dongahn commented
Ah... probably, e13b40b and 668c205

2020-10-17 23:02 UTC, dongahn requested changes
@garlick: This is a great improvement and step into the right direction! 

I made some mostly minor points.

But having a guaranteed way to receive the `.scheduling` key needs to be described. (see the inline comment above.).

@milroy and @SteVwonder : after you are done with IPDPS submission, it would be great for your to review this. I can see various ways to extend this to support general elasticity and multi-tired storage scheduling.

2022-01-09 17:12 UTC, garlick commented
IMHO we should just document the current protocol in RFC 28 as version 1 and revisit this discussion  for  version 2.  Closing this PR for now.

2022-01-09 17:12 UTC, closed without merging